# 01 — Persiapan & Cek Environment

**Project:** Analisis Deret Waktu Harga Bahan Pokok (Bapok) Surabaya  
**Konteks:** Bagian dari EWS (Early Warning System) Bapok Surabaya  

---

## Tujuan notebook ini

Fase 0 = memastikan semua **alat belajar** siap sebelum masuk ke analisis data.

Kamu akan:
1. Cek versi Python & paket
2. Import semua library
3. Set opsi tampilan
4. Cek file data ada
5. Tes baca data + lihat 5 baris pertama

> **Cara pakai:** baca penjelasan tiap sel, jalankan kode (Shift+Enter), lalu isi sel bertanda `# TODO`.

## 0.1 — Cek versi Python

Kita cek dulu Python mana yang dipakai notebook ini. Pastikan interpreter-nya sama dengan yang lolos di `check_env.py`.

In [2]:
import sys

print("Versi Python :", sys.version.split()[0])
print("Lokasi       :", sys.executable)

Versi Python : 3.13.9
Lokasi       : c:\Users\LENOVO\anaconda3\python.exe

## 0.2 — Import library

Semua library inti untuk analisis deret waktu:

| Library | Kegunaan |
|---|---|
| `pandas` | olah tabel data |
| `numpy` | hitungan angka |
| `matplotlib` / `seaborn` | gambar grafik |
| `statsmodels` | model deret waktu (ARIMA, ETS, ADF, ACF/PACF) |
| `sklearn` | metrik evaluasi (MAE, RMSE, MAPE) |

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# statsmodels dipakai nanti di Fase 2 & 3, kita cek importnya sudah jalan
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller

from sklearn.metrics import mean_absolute_error, mean_squared_error

from pathlib import Path

print("Semua library berhasil di-import.")

Semua library berhasil di-import.

## 0.3 — Opsi tampilan

Supaya output tabel enak dibaca (angka tidak jadi notasi ilmiah, kolom tidak terpotong).

In [4]:
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 120)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

# Pengaturan grafik default
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (12, 4)
plt.rcParams["figure.dpi"] = 100

print("Opsi tampilan diset.")

Opsi tampilan diset.

## 0.4 — Tentukan lokasi file data

Kita pakai `pathlib.Path` supaya path aman di Windows.

> **Penting:** kita **tidak menyalin** file data. Notebook hanya membaca dari lokasi asli.

In [5]:
# Folder induk project (tempat file CSV berada)
BASE = Path(r"C:\Users\LENOVO\Documents\TOOUUGUAASS\SMT 5\BRIDA PROJECTS")

# Dua file data utama
FILE_HARIAN = BASE / "rekap_januari_2024_harian.csv"   # data mentah per pasar
FILE_REKAP  = BASE / "rekap_januari_2024_rekap.csv"    # agregat + kolom het_hapk

# Folder output (untuk simpan hasil nanti)
OUTPUT = Path(r"C:\Users\LENOVO\Documents\TOOUUGUAASS\SMT 5\BRIDA PROJECTS\notebooks\output")
OUTPUT.mkdir(exist_ok=True)

print("BASE  :", BASE)
print("OUTPUT:", OUTPUT)

BASE  : C:\Users\LENOVO\Documents\TOOUUGUAASS\SMT 5\BRIDA PROJECTS
OUTPUT: C:\Users\LENOVO\Documents\TOOUUGUAASS\SMT 5\BRIDA PROJECTS\notebooks\output

## 0.5 — Cek file data ada atau tidak

In [6]:
for label, f in [("HARIAN (per pasar)", FILE_HARIAN), ("REKAP (agregat)", FILE_REKAP)]:
    status = "ADA" if f.exists() else "TIDAK ADA"
    print(f"[{status}] {label} -> {f.name}")

[ADA] HARIAN (per pasar) -> rekap_januari_2024_harian.csv
[ADA] REKAP (agregat) -> rekap_januari_2024_rekap.csv

## 0.6 — Tes baca data

Kalau dua sel berikut jalan tanpa error, berarti environment **lengkap & siap**.

In [7]:
df_harian = pd.read_csv(FILE_HARIAN)
df_rekap  = pd.read_csv(FILE_REKAP)

print("Data harian :", df_harian.shape, "(baris, kolom)")
print("Data rekap  :", df_rekap.shape, "(baris, kolom)")

Data harian : (13020, 9) (baris, kolom)
Data rekap  : (1855, 6) (baris, kolom)

In [8]:
df_harian.head()

      tanggal kategori      komoditas satuan               pasar     harga  rata_harian  rata_hitung  selisih_rata
0  2024-01-01    BERAS  Beras Premium     Kg    Pasar Tambahrejo 14,000.00    13,985.71    13,985.71          0.00
1  2024-01-01    BERAS  Beras Premium     Kg   Pasar Pucang Anom 14,000.00    13,985.71    13,985.71          0.00
2  2024-01-01    BERAS  Beras Premium     Kg     Pasar Wonokromo 13,900.00    13,985.71    13,985.71          0.00
3  2024-01-01    BERAS  Beras Premium     Kg  Pasar Genteng Baru 14,000.00    13,985.71    13,985.71          0.00
4  2024-01-01    BERAS  Beras Premium     Kg        Pasar Pabean 14,000.00    13,985.71    13,985.71          0.00

In [9]:
df_rekap.head()

      tanggal kategori      komoditas  harga_rata  het_hapk    fluktuasi
0  2024-01-01    BERAS  Beras Premium   13,985.71 12,800.00  14.28571429
1  2024-01-02    BERAS  Beras Premium   13,985.71 12,800.00  14.28571429
2  2024-01-03    BERAS  Beras Premium   13,985.71 12,800.00  14.28571429
3  2024-01-04    BERAS  Beras Premium   13,985.71 12,800.00  14.28571429
4  2024-01-05    BERAS  Beras Premium   13,985.71 12,800.00  14.28571429

---

## 📝 LATIHAN (isi sendiri)

Sel di bawah ini bertanda `# TODO`. Coba isi & jalankan. Kalau bingung, lihat lagi sel-sel di atas.

**Latihan 1:** Tampilkan hanya kolom `tanggal`, `komoditas`, `harga` dari `df_harian` untuk 10 baris pertama.

**Petunjuk:** `.head(10)` dan bisa pilih kolom pakai `df[['kolom1', 'kolom2']]`.

In [10]:
# TODO: tulis kode di bawah ini
# Contoh awal:
# df_harian[['tanggal', 'komoditas', 'harga']].head(10)
    
df_rekap[['tanggal', 'komoditas', 'harga_rata', 'het_hapk']].head(50)

       tanggal                 komoditas  harga_rata  het_hapk
0   2024-01-01             Beras Premium   13,985.71 12,800.00
1   2024-01-02             Beras Premium   13,985.71 12,800.00
2   2024-01-03             Beras Premium   13,985.71 12,800.00
3   2024-01-04             Beras Premium   13,985.71 12,800.00
4   2024-01-05             Beras Premium   13,985.71 12,800.00
5   2024-01-06             Beras Premium   13,985.71 12,800.00
6   2024-01-07             Beras Premium   13,985.71 12,800.00
7   2024-01-08             Beras Premium   13,985.71 12,800.00
8   2024-01-09             Beras Premium   13,985.71 12,800.00
9   2024-01-10             Beras Premium   13,985.71 12,800.00
10  2024-01-11             Beras Premium   13,985.71 12,800.00
11  2024-01-12             Beras Premium   13,985.71 12,800.00
12  2024-01-13             Beras Premium   13,985.71 12,800.00
13  2024-01-14             Beras Premium   13,985.71 12,800.00
14  2024-01-15             Beras Premium   14,000.00 12,800.00
15  2024-01-16             Beras Premium   14,000.00 12,800.00
16  2024-01-17             Beras Premium   14,000.00 12,800.00
17  2024-01-18             Beras Premium   14,000.00 12,800.00
18  2024-01-19             Beras Premium   14,000.00 12,800.00
19  2024-01-20             Beras Premium   14,000.00 12,800.00
20  2024-01-21             Beras Premium   14,000.00 12,800.00
21  2024-01-22             Beras Premium   14,000.00 12,800.00
22  2024-01-23             Beras Premium   14,000.00 12,800.00
23  2024-01-24             Beras Premium   14,000.00 12,800.00
24  2024-01-25             Beras Premium   14,000.00 12,800.00
25  2024-01-26             Beras Premium   14,000.00 12,800.00
26  2024-01-27             Beras Premium   14,000.00 12,800.00
27  2024-01-28             Beras Premium   14,000.00 12,800.00
28  2024-01-29             Beras Premium   14,000.00 12,800.00
29  2024-01-30             Beras Premium   14,000.00 12,800.00
30  2024-01-31             Beras Premium   14,000.00 12,800.00
31  2024-01-01  Beras IR.64 Medium Bulog   10,900.00       NaN
32  2024-01-02  Beras IR.64 Medium Bulog   10,900.00       NaN
33  2024-01-03  Beras IR.64 Medium Bulog   10,900.00       NaN
34  2024-01-04  Beras IR.64 Medium Bulog   10,900.00       NaN
35  2024-01-05  Beras IR.64 Medium Bulog   10,900.00       NaN
36  2024-01-06  Beras IR.64 Medium Bulog   10,900.00       NaN
37  2024-01-07  Beras IR.64 Medium Bulog   10,900.00       NaN
38  2024-01-08  Beras IR.64 Medium Bulog   10,900.00       NaN
39  2024-01-09  Beras IR.64 Medium Bulog   10,900.00       NaN
40  2024-01-10  Beras IR.64 Medium Bulog   10,900.00       NaN
41  2024-01-11  Beras IR.64 Medium Bulog   10,900.00       NaN
42  2024-01-12  Beras IR.64 Medium Bulog   10,900.00       NaN
43  2024-01-13  Beras IR.64 Medium Bulog   10,900.00       NaN
44  2024-01-14  Beras IR.64 Medium Bulog   10,900.00       NaN
45  2024-01-15  Beras IR.64 Medium Bulog   10,900.00       NaN
46  2024-01-16  Beras IR.64 Medium Bulog   10,900.00       NaN
47  2024-01-17  Beras IR.64 Medium Bulog   10,900.00       NaN
48  2024-01-18  Beras IR.64 Medium Bulog   10,900.00       NaN
49  2024-01-19  Beras IR.64 Medium Bulog   10,900.00       NaN

**Latihan 2:** Ada berapa **pasar unik** di `df_harian`?

**Petunjuk:** coba `df_harian['pasar'].nunique()` atau `df_harian['pasar'].unique()`.

In [13]:
# TODO: tulis kode di bawah ini
df_rekap['fluktuasi'].unique()

array(['14.28571429', '0', '#VALUE!', '-66.66666667', '1200',
       '-71.42857143', '428.5714286', '2100', '714.2857143', '-1000',
       '1000', '-1285.714286', '357.1428571', '-857.1428571',
       '-83.33333333', '857.1428571', '-571.4285714', '-416.6666667',
       '-333.3333333', '571.4285714', '11857.14286', '-285.7142857',
       '-33857.14286', '-428.5714286', '-4714.285714', '333.3333333',
       '142.8571429', '-833.3333333', '-2714.285714', '4000',
       '285.7142857', '-142.8571429'], dtype=object)

**Latihan 3:** Tampilkan jumlah baris data `df_rekap` untuk komoditas `'Beras Premium'`.

**Petunjuk:** filter dulu -> `df_rekap[df_rekap['komoditas'] == 'Beras Premium']`, lalu hitung jumlah barisnya dengan `len(...)` atau `.shape`.

In [12]:
# TODO: tulis kode di bawah ini

---

### ✅ Selesai Fase 0 kalau:
- [ ] Semua sel di atas jalan tanpa error
- [ ] Kamu sudah coba 3 latihan tadi
- [ ] `check_env.py` di terminal juga sudah lolos

Kalau sudah, lanjut ke **Fase 1 (Load & Cleaning)** — kita akan bersihkan data ini dan menambah kolom `het_hapk`.